<?php

/**
 * @file
 * Loads PACE js.
 */

/**
 * Implements hook_config_info().
 */
function pace_config_info() {
  $settings['pace.settings'] = array(
    'label' => t('PACE Settings'),
    'group' => t('PACE'),
  );
  return $settings;
}

/**
 * Implements hook_permission().
 */
function pace_permission() {
  return array(
    'manage PACE settings' => array(
      'title' => t('Manage PACE settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function pace_menu() {
  $items = array();

  $items['admin/config/user-interface/pace'] = array(
    'title' => 'PACE Settings',
    'description' => 'Administer PACE progress bar settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('pace_settings_form'),
    'access arguments' => array('manage PACE settings'),
    'file' => 'pace.admin.inc',
  );

  return $items;
}

/**
 * Implements template_preprocess().
 */
function pace_preprocess(&$variables) {
  // Check if PACE is disabled for admin pages and don't load it.
  if(!config_get('pace.settings', 'pace_load_on_admin_enabled')) {
    if(!path_is_admin(current_path())) {
      load_pace();
    }
  }
  else {
    load_pace();
  }
}

function load_pace() {
  backdrop_add_js(backdrop_get_path('module','pace') . '/js/pace.min.js', array('weight' => -100, 'preprocess' => TRUE));
  backdrop_add_css(backdrop_get_path('module','pace') . '/css/' . config_get('pace.settings', 'pace_theme'), array('weight' => -100, 'preprocess' => TRUE));

  if(config_get('pace.settings', 'pace_custom_color_enabled')) {
    $customcolor = '';
    $customcolor .= '.pace .pace-progress {';
    $customcolor .= 'background: #';
    $customcolor .= config_get('pace.settings', 'pace_custom_color_value');
    $customcolor .= '; }';
    backdrop_add_css($customcolor,'inline');
  }
}
